channel_tag: "Goodbaye_filtering"
telegram_link: "https://t.me/Goodbaye_filtering"
group_link: "https://t.me/CONFIG_V2RAY_VIP"

sources:
  - "https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/mix"
  - "https://raw.githubusercontent.com/roosterkid/openproxylist/main/V2RAY_BASE64.txt"
  - "https://manager.onetwothree123.ir/"
  - "https://raw.githubusercontent.com/0xRadikal/Free-v2ray-Configs/main/top100.txt"
  - "https://raw.githubusercontent.com/Q3dlaXpoaQ/Q3dlaXpoaQ.github.io/refs/heads/main/APIs/cg1.txt"
  - "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_1.txt"
  - "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_1.txt"
  - "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt"
  - "https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/refs/heads/main/configs/ir/vless.txt"
  - "https://raw.githubusercontent.com/Surfboardv2ray/TGParse/refs/heads/main/splitted/hysteria2"
  - "https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/vless.txt"
  - "https://raw.githubusercontent.com/0xRadikal/Free-v2ray-Configs/refs/heads/main/protocols/hysteria2.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no1.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no2.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no3.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no4.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no5.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no6.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no7.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no8.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no9.txt"
  - "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/V2RAY_SUB/refs/heads/main/v2ray_configs_no10.txt"
  - "https://raw.githubusercontent.com/MohammadBahemmat/V2ray-Collector/main/all_servers.txt"
  - "https://raw.githubusercontent.com/MahanKenway/Freedom-V2Ray/main/configs/vless_sub.txt"

max_workers: 50
max_candidates: 1500
top_n_final: 500
chunk_size: 150
stability_rounds: 2
tcp_timeout: 1.5
tls_timeout: 2.5
max_ping_ms: 400
max_tls_ping_ms: 600
include_vmess: true
golden_ports_t1: [443, 2053, 2083, 2087, 2096, 8443]
golden_ports_t2: [80, 2052, 2082, 2086, 8080, 8880]
golden_bonus_t1: 180
golden_bonus_t2: 80
golden_t1_reality_extra: 60
golden_only_tls: true
golden_filter_only: false
ewma_decay: 0.7
min_history_samples: 3
sni_check: true
geo_max_concurrent: 20
geo_timeout: 3.0
geo_max_calls_per_run: 800
real_test_enabled: true
real_test_max_candidates: 250
real_test_concurrency: 15
real_test_url: "http://cp.cloudflare.com/generate_204"
real_test_timeout: 5.0
db_path: "history.db"
